### ISSUE TITLE
Error - plotly import

### ISSUE THREAD

**Issue by capelastegui** [sky-uk/anticipy#183]
Broken CI in https://github.com/sky-uk/anticipy/commit/841544df784059baa26024715d166448226d85a7 , most likely due to conflict in latest plotly version

```python
import plotly as py
py.subplots # Works with plotly <= 4.5.2
# plotly >= 4.9.0 crashes with 
#  AttributeError: 'module' object has no attribute 'subplots'
```

**Comment by capelastegui** [comment]
Looks like we need to explicitly import subplots, for some reason:

```
import plotly
plotly.subplots
Traceback (most recent call last):
  File "/Users/pec21/PycharmProjects/anticipy/virtual3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-9304b4589615>", line 1, in <module>
    plotly.subplots
AttributeError: module 'plotly' has no attribute 'subplots'
import plotly.subplots
plotly.subplots
Out[5]: <module 'plotly.subplots' from '/Users/pec21/PycharmProjects/anticipy/virtual3/lib/python3.6/site-packages/plotly/subplots.py'>
```
